import { supabase } from './supabase'
import type {
  Snag, SnagEvent, SnagFormLink, SnagSite, SnagStatus, WaStatus,
} from '../types/snags'
import type { Employee } from '../types'

// ── Access ────────────────────────────────────────────────────────────────────
// Mirrors public.can_view_snags() / can_manage_snags() in supabase/sql/snags.sql.
// These are the UX layer only — RLS is what actually enforces it.

export function canViewSnags(employee: Employee | null): boolean {
  if (!employee || !employee.is_active) return false
  return employee.snag_viewer || employee.snag_owner
    || employee.role === 'admin' || employee.role === 'founder'
}

export function canManageSnags(employee: Employee | null): boolean {
  if (!employee || !employee.is_active) return false
  return employee.snag_owner || employee.role === 'admin'
}

// ── Reports ───────────────────────────────────────────────────────────────────

export async function fetchSnags(): Promise<Snag[]> {
  const { data, error } = await supabase
    .from('snag_reports')
    .select('*, project:projects(name, code)')
    .order('created_at', { ascending: false })
  if (error) throw error
  return (data ?? []) as Snag[]
}

export async function fetchSnagEvents(snagId: string): Promise<SnagEvent[]> {
  const { data, error } = await supabase
    .from('snag_events')
    .select('*, actor:employees(name)')
    .eq('snag_id', snagId)
    .order('created_at', { ascending: true })
  if (error) throw error
  return (data ?? []) as SnagEvent[]
}

/**
 * Real WhatsApp delivery status for notification events.
 *
 * The Plumbline gateway queues sends and returns immediately, so a 'notified'
 * event only proves the message was accepted. wa_messages.status is the truth,
 * read through a narrow SECURITY DEFINER function rather than by granting snag
 * viewers access to the company-wide message log.
 */
export async function fetchWaStatus(ids: string[]): Promise<Record<string, WaStatus>> {
  if (!ids.length) return {}
  const { data, error } = await supabase.rpc('snag_wa_status', { p_ids: ids })
  if (error) throw error
  const out: Record<string, WaStatus> = {}
  for (const row of (data ?? []) as { id: string; status: WaStatus }[]) {
    out[row.id] = row.status
  }
  return out
}

/** Advance (or close) a snag, stamping the matching lifecycle timestamp and
 *  writing the audit event. */
export async function updateSnagStatus(
  snag: Snag,
  to: SnagStatus,
  actorId: string,
  note?: string,
): Promise<void> {
  const now = new Date().toISOString()
  const patch: Record<string, unknown> = { status: to }

  // first_response_at marks when someone actually picked the snag up — set once.
  if (!snag.first_response_at && to !== 'open') patch.first_response_at = now
  if (to === 'resolved' && !snag.resolved_at) patch.resolved_at = now
  if (to === 'closed') {
    patch.closed_at = now
    if (!snag.resolved_at) patch.resolved_at = now
  }
  if (note?.trim()) patch.resolution_note = note.trim()

  const { error } = await supabase.from('snag_reports').update(patch).eq('id', snag.id)
  if (error) throw error

  const { error: evErr } = await supabase.from('snag_events').insert({
    snag_id: snag.id,
    actor_id: actorId,
    event_type: 'status_changed',
    from_status: snag.status,
    to_status: to,
    note: note?.trim() || null,
  })
  if (evErr) throw evErr
}

export async function addSnagComment(
  snagId: string, actorId: string, note: string,
): Promise<void> {
  const { error } = await supabase.from('snag_events').insert({
    snag_id: snagId,
    actor_id: actorId,
    event_type: 'comment',
    note: note.trim(),
  })
  if (error) throw error
}

// ── Sites ─────────────────────────────────────────────────────────────────────

/** Only the handed-over sites Saksham issues client links for — not every
 *  project in the Hub. Whitelisted by projects.snag_enabled. */
export async function fetchSnagSites(): Promise<SnagSite[]> {
  const { data, error } = await supabase
    .from('projects')
    .select('id, code, name, snag_group')
    .eq('snag_enabled', true)
    .eq('is_active', true)
    .order('name')
  if (error) throw error
  return (data ?? []) as SnagSite[]
}

// ── Form links ────────────────────────────────────────────────────────────────

/** Every link, for the Client Links tab. Small table (one row per project, plus
 *  revoked history), so it's cheaper to fetch once and group in memory than to
 *  query per project. */
export async function fetchAllFormLinks(): Promise<SnagFormLink[]> {
  const { data, error } = await supabase
    .from('snag_form_links')
    .select('*')
    .order('created_at', { ascending: false })
  if (error) throw error
  return (data ?? []) as SnagFormLink[]
}

/** The token is generated by a column default, so it never travels from the
 *  browser and cannot be chosen by the caller. */
export async function createFormLink(
  projectId: string, createdBy: string, label?: string,
): Promise<SnagFormLink> {
  const { data, error } = await supabase
    .from('snag_form_links')
    .insert({ project_id: projectId, created_by: createdBy, label: label?.trim() || null })
    .select('*')
    .single()
  if (error) throw error
  return data as SnagFormLink
}

/** One link covering every site in a group. The client picks their site on the
 *  form; the report is still filed against that one project. */
export async function createGroupFormLink(
  groupKey: string, createdBy: string,
): Promise<SnagFormLink> {
  const { data, error } = await supabase
    .from('snag_form_links')
    .insert({ group_key: groupKey, created_by: createdBy, label: `${groupKey} — all sites` })
    .select('*')
    .single()
  if (error) throw error
  return data as SnagFormLink
}

export async function revokeFormLink(id: string): Promise<void> {
  const { error } = await supabase
    .from('snag_form_links')
    .update({ is_active: false, revoked_at: new Date().toISOString() })
    .eq('id', id)
  if (error) throw error
}

export function snagFormUrl(token: string): string {
  return `${window.location.origin}/s/snag?t=${encodeURIComponent(token)}`
}
